// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchBook(arg1, arg2) {
  return window['go']['backend']['BookHandler']['SearchBook'](arg1, arg2);
}

export function SearchChapter(arg1, arg2) {
  return window['go']['backend']['BookHandler']['SearchChapter'](arg1, arg2);
}

export function SearchContent(arg1, arg2) {
  return window['go']['backend']['BookHandler']['SearchContent'](arg1, arg2);
}
