// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSites(arg1) {
  return window['go']['backend']['BookSitesHandler']['AddSites'](arg1);
}

export function DelSites(arg1) {
  return window['go']['backend']['BookSitesHandler']['DelSites'](arg1);
}

export function EditSites(arg1) {
  return window['go']['backend']['BookSitesHandler']['EditSites'](arg1);
}

export function GetBooks() {
  return window['go']['backend']['BookSitesHandler']['GetBooks']();
}

export function GetSites() {
  return window['go']['backend']['BookSitesHandler']['GetSites']();
}
