// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {backend} from '../models';

export function AddSites(arg1:models.BookSite):Promise<void>;

export function DelSites(arg1:models.BookSite):Promise<void>;

export function EditSites(arg1:models.BookSite):Promise<void>;

export function GetBooks():Promise<Array<backend.Book>>;

export function GetSites():Promise<Array<models.BookSite>>;
