// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function SearchBook(arg1:string,arg2:number):Promise<Array<models.Book>>;

export function SearchBookByRule(arg1:string,arg2:models.BookSiteUri):Promise<Array<models.Book>>;

export function SearchChapter(arg1:models.Book,arg2:models.BookSite):Promise<Array<models.Chapter>>;

export function SearchContent(arg1:models.Chapter,arg2:models.BookSite):Promise<models.Content>;
