// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet2(arg1) {
  return window['go']['backend']['GreetHandler2']['Greet2'](arg1);
}
