// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSpeakSample() {
  return window['go']['backend']['SpeakerHandler']['DeleteSpeakSample']();
}

export function SpeakSample() {
  return window['go']['backend']['SpeakerHandler']['SpeakSample']();
}

export function Text2Speak(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['SpeakerHandler']['Text2Speak'](arg1, arg2, arg3, arg4);
}

export function Text2Speech(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['SpeakerHandler']['Text2Speech'](arg1, arg2, arg3, arg4, arg5);
}
